### ⚡ **CDD-20: Performance e Arrays com NumPy**

**Autora:** Tina Almeida

**Data:** 11/02/2026

**Dataset:** `fifa19.cvs`

---
### 🎯 Objetivos
Comparar a eficiência de memória e processamento entre **Listas Python** e **Arrays NumPy**



In [32]:
import pandas as pd
import numpy as np
import os # Biblioteca para verificar se o arquivo existe
import sys # Biblioteca para permitir medir memória
import time # Biblioteca para medir tempo de execução

# Definindo o caminho do arquivo CSV
caminho = '../dados/fifa19/fifa19.csv'
encoding = 'latin-1'

# Carregando o dataset usando pandas
if os.path.exists(caminho):
    print(" 🔵 Carregando o dataset...")
    print(f" 🟢 Caminho do arquivo: {caminho}")
    df = pd.read_csv(caminho, encoding=encoding)
    print(" ✅ Dataset carregado com sucesso!")
    print(f"Seu arquivo possui {df.shape[0]} linhas e {df.shape[1]} colunas.")
else:
    print("🔴 Arquivo não encontrado.")


 🔵 Carregando o dataset...
 🟢 Caminho do arquivo: ../dados/fifa19/fifa19.csv
 ✅ Dataset carregado com sucesso!
Seu arquivo possui 18207 linhas e 89 colunas.


1️⃣ Criando Dimensões (3D, 2D, 1D) 📐

In [33]:
print("--- 📐 Criando Arrays Multidimensionais ---")

# 1. Array 1D (Vetor): Uma linha de penalties
# fillna(0) garante que não tenha valores NaN
array_1d = np.array(df['Penalties'].fillna(0))
print(f" 1D (Penalties): {array_1d.shape}\nExemplo dos 5 primeiros: {array_1d[:5]}")

# 2. Array 2D (Matriz): Penalties e Overall
# Duas colunas numéricas
array_2d = np.array(df[['Penalties', 'Overall']].fillna(0))
print(f" \n2D (Penalties, Overall): {array_2d.shape}\nExemplo dos 5 primeiros:\n{array_2d[:5]}")

# 3. Array: 3D (Tensor/Cubo): Penalties, Overall e Age
# Três colunas numéricas
dados_recorte = array_1d[:27]
array_3d = dados_recorte.reshape(3, 3, 3)
print(f" \n3D (Penalties, Overall, Age): {array_3d.shape}\nExemplo dos 5 primeiros:\n{array_3d[:5]}")

--- 📐 Criando Arrays Multidimensionais ---
 1D (Penalties): (18207,)
Exemplo dos 5 primeiros: [75. 85. 81. 40. 79.]
 
2D (Penalties, Overall): (18207, 2)
Exemplo dos 5 primeiros:
[[75. 94.]
 [85. 94.]
 [81. 92.]
 [40. 91.]
 [79. 91.]]
 
3D (Penalties, Overall, Age): (3, 3, 3)
Exemplo dos 5 primeiros:
[[[75. 85. 81.]
  [40. 79. 86.]
  [82. 85. 75.]]

 [[11. 88. 73.]
  [50. 75. 54.]
  [86. 90. 79.]]

 [[25. 27. 60.]
  [85. 47. 83.]
  [50. 70. 61.]]]


2️⃣ Batalha da Memória (Bytes) 💾

In [34]:
print("--- 💾 Comparativo de Memória (RAM) ---")

# Criando uma lista de Python "Pura" a partir do array 1D
lista_python = list(array_1d)

# Calculando o tamanho da Lista Python (Ponteiros + Objetos)
# Listas guardam referências a objetos, por isso são mais pesadas
tamanho_lista = sys.getsizeof(lista_python) + (sys.getsizeof(lista_python[0]) * len(lista_python))

# Calculando o tamanho do Array NumPy (Dados compactados em C)
tamanho_numpy = array_1d.nbytes

print(f"\n📦 Lista Python: {tamanho_lista} bytes")
print(f"📦 Array NumPy: {tamanho_numpy} bytes")

diferenca_memoria = tamanho_lista / tamanho_numpy
print(f"\n💾 Conclusão: Numpy é {diferenca_memoria:.2f} vezes mais eficiente em termos de memória")

--- 💾 Comparativo de Memória (RAM) ---

📦 Lista Python: 728344 bytes
📦 Array NumPy: 145656 bytes

💾 Conclusão: Numpy é 5.00 vezes mais eficiente em termos de memória


3️⃣ Batalha de Velocidade (Tempo) ⏱️

In [35]:
print ("--- ⏱️ Comparativo de Velocidade (Soma) ---")

# Teste Python Puro (sum)
inicio_python = time.time()
soma_python = sum(lista_python)
fim_python = time.time()
tempo_python = fim_python - inicio_python

# Teste NumPy (np.sum)
inicio_numpy = time.time()
soma_numpy = np.sum(array_1d)
fim_numpy = time.time()
tempo_numpy = fim_numpy - inicio_numpy

print(f"\n🐢 Tempo Python: {tempo_python:.6f} segundos")
print(f"⚡ Tempo NumPy: {tempo_numpy:.6f} segundos")

if tempo_numpy > 0:
    velocidade_ganho = tempo_python / tempo_numpy
    print(f"\n🚀 Conclusão: NumPy é {velocidade_ganho:.2f} vezes mais rápido que Python")

--- ⏱️ Comparativo de Velocidade (Soma) ---

🐢 Tempo Python: 0.001687 segundos
⚡ Tempo NumPy: 0.000792 segundos

🚀 Conclusão: NumPy é 2.13 vezes mais rápido que Python


4️⃣ Seleção e Filtros (Brasil e Penalties) 🔍

In [36]:
print("--- 🔍 Filtros e Seleção de Dados ---")

# Convertendo colunas de texto para arrays NumPy
nacionalidades = df['Nationality'].values
nomes = df['Name'].values

# 1. Filtro Boolean: Quem é Brasileiro?
filtro_brasileiros = nacionalidades == 'Brazil'
print(f"\n🇧🇷 Jogadores Brasileiros: {len(nomes[filtro_brasileiros])}")

# 2. Filtrando Arrays com Arrays
# Pagamos os nomes e os penalties para os brasileiros
nomes_brasileiros = nomes[filtro_brasileiros]
penalties_brasileiros = array_1d[filtro_brasileiros]

# 3. Quem são os maiores cobradores de pênalti brasileiros?
filtro_craques = penalties_brasileiros > 80

craques_brasileiros = nomes_brasileiros[filtro_craques]

print("\n⚽ Craques Brasileiros com Penalties > 80:")
#Zip junta as duas listas para mostrar nome e penalties juntos
for nome, penalty, age in zip(craques_brasileiros, penalties_brasileiros[filtro_craques], df['Age'].values[filtro_brasileiros][filtro_craques]):
    print(f" - {nome} de {age} anos : {penalty} de Penalties")

--- 🔍 Filtros e Seleção de Dados ---

🇧🇷 Jogadores Brasileiros: 827

⚽ Craques Brasileiros com Penalties > 80:
 - Neymar Jr de 26.0 anos : 81.0 de Penalties
 - Fabinho de 24.0 anos : 91.0 de Penalties
 - Jonas de 34.0 anos : 84.0 de Penalties
 - Elkeson de 28.0 anos : 85.0 de Penalties
 - Vágner Love de 34.0 anos : 83.0 de Penalties
 - Fernandão de 31.0 anos : 83.0 de Penalties


5️⃣ Estatística Rápidas (Agregação) 📊

In [37]:
print("--- 📊 Estatísticas Gerais com NumPy ---")

# 1. Média de Penalties
print(f"\nMédia Geral de Penalties: {np.mean(array_1d):.2f}")
# 2. Melhor Cobrador de Penalties
print(f"Melhor Cobrador de Penalties (Nota Máxima): {np.max(array_1d)}")
# 3. Jogador Pior Cobrador de Penalties
print(f"Pior Cobrador de Penalties (Nota Mínima): {np.min(array_1d)}")
# 4. Desvio Padrão de Penalties
print(f"Desvio Padrão de Penalties (Variação): {np.std(array_1d):.2f}")

--- 📊 Estatísticas Gerais com NumPy ---

Média Geral de Penalties: 48.42
Melhor Cobrador de Penalties (Nota Máxima): 92.0
Pior Cobrador de Penalties (Nota Mínima): 0.0
Desvio Padrão de Penalties (Variação): 15.88
